/**
 * Created by cifer on 2017/8/23.
 */
export const CONN_SUCCESS = "CONN_SUCCESS"
export const CONN_DISABLE = "CONN_DISABLE"
export const CONN_TRYING = "CONN_TRYING"

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_DISABLE = "AUTH_DISABLE"
export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_ERROR = "AUTH_ERROR"

export const GAME_GET_BAG = "GAME_GET_BAG"
export const GAME_GET_BAG_SUCCESS = "GAME_GET_BAG_SUCCESS"
export const GAME_GET_PARTY = "GAME_GET_PARTY"
export const GAME_GET_PARTY_SUCCESS = "GAME_GET_PARTY_SUCCESS"
export const GAME_GET_TIME = "GAME_GET_TIME"
export const GAME_GET_TIME_SUCCESS = "GAME_GET_TIME_SUCCESS"
export const GAME_GET_SCENE = "GAME_GET_SCENE"
export const GAME_GET_SCENE_SUCCESS = "GAME_GET_SCENE_SUCCESS"
