/**
 * Created by cifer on 2017/8/23.
 */

const CONN_REQUIRE = "CONN_REQUIRE"
const CONN_SUCCESS = "CONN_SUCCESS"
const CONN_DISABLE = "CONN_DISABLE"
const CONN_TRYING = "CONN_TRYING"

const AUTH_SUCCESS = "AUTH_SUCCESS"
const AUTH_DISABLE = "AUTH_DISABLE"
const AUTH_LOGIN = "AUTH_LOGIN"
const AUTH_ERROR = "AUTH_ERROR"

export default {
    CONN_DISABLE, CONN_REQUIRE, CONN_SUCCESS, CONN_TRYING,
    AUTH_DISABLE, AUTH_ERROR, AUTH_LOGIN, AUTH_SUCCESS
}